# Generated by Django 5.2.10 on 2026-02-21 02:06

import django.core.validators
import django.db.models.deletion
import reports.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('bartender', 'Bartender'), ('barback', 'Barback'), ('security', 'Security')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClosingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_date', models.DateField(default=reports.models.default_business_date)),
                ('total_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('eighty_six_list', models.TextField(blank=True)),
                ('shift_notes', models.TextField(blank=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_reports_created', to=settings.AUTH_USER_MODEL)),
                ('emailed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closing_reports_emailed', to=settings.AUTH_USER_MODEL)),
                ('barbacks', models.ManyToManyField(blank=True, related_name='closing_reports_as_barback', to='reports.staffmember')),
                ('bartenders', models.ManyToManyField(blank=True, related_name='closing_reports_as_bartender', to='reports.staffmember')),
                ('security', models.ManyToManyField(blank=True, related_name='closing_reports_as_security', to='reports.staffmember')),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaidOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter a positive dollar amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_outs', to='reports.closingreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
