# Generated by Django 5.2.9 on 2025-12-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_eventpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpost',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='eventpost',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower shows first'),
        ),
    ]
