# Generated by Django 5.2.12 on 2026-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cocktail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='homepage_panels/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
