# Generated by Django 5.2.12 on 2026-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homepagepanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='kitchen_menus/')),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='eventpost',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='homepagepanel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
